server:
  port: 19060

spring:
  application:
    name: hub
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/