spring:
  application:
    name: gateway
  datasource:
    url: jdbc:h2:mem:i4u
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5  # 초당 요청 제한 개수
                redis-rate-limiter.burstCapacity: 10 # 최대 요청 버스트 가능 개수
                redis-rate-limiter.requestedTokens: 1 # 요청당 차감할 토큰 개수
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedTokens: 1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
  redis:
    host: localhost
    port: 6379

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

gateway:
  url: localhost:19091

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: "your-secret-key-here"
